### ISSUE TITLE
Hanging indefinitely, encoding error

### ISSUE THREAD

**Issue by overfl0wd** [kootenpv/gittyleaks#11]
Hi,

Occasionally with certain repos the tool hangs forever, and sending SIGINT throws the following error:

![image](https://user-images.githubusercontent.com/48800966/59202339-42802780-8b6a-11e9-9cbe-bcd7173af466.png)

This doesn't happen when running within smaller directories within repos, but this happens when running at the repository root.

**Comment by overfl0wd** [comment]
I'm running Gittyleaks version 1.1.4 and Python 3.6.7

**Comment by kootenpv** [comment]
Hey, thanks for posting! Is there a public repo I can reproduce this with :)?

**Comment by overfl0wd** [comment]
Unfortunately I'm on testing on private org repositories :/ 

I'm thinking it may be hanging on compiled code (build artifacts) lingering in the repo. Would this be expected behavior?

**Comment by overfl0wd** [comment]
FWIW, going off that ^ idea, I pulled a list of all file extensions in the repository. This might be why it's hanging.. 

`Config
GIF
Master
SCC
asax
ascx
asmx
aspx
cd
cmd
config
cs
cshtml
csproj
css
datasource
disco
eot
exe
feature
gif
gitignore
htm
html
ico
idx
js
json
loadtest
manifest
map
md
myapp
otf
pack
pdb
pdf
png
ps1
refresh
resx
sample
settings
sln
sql
ssc
suo
svc
svcinfo
svcmap
svg
testrunconfig
testsettings
ts
ttf
txt
user
vb
vbproj
vdproj
vsmdi
vspscc
vssscc
webinfo
webtest
woff
woff2
wsdl
xaml
xml
xsd
xslt`

**Comment by kootenpv** [comment]
Perhaps if it would take into account a `.gitignore` file, things would be solved?

**Comment by overfl0wd** [comment]
Those files are (unfortunately for us) intended to be checked into master. They are legitimate items in the repository.

**Comment by overfl0wd** [comment]
Perhaps  Gittyleaks could ignore known incompatible filetypes. I will do some testing and see what it's hanging on

**Comment by overfl0wd** [comment]
@kootenpv while I'm testing.. are you aware of any file formats that you've seen Gittyleaks have issues with?

**Comment by kootenpv** [comment]
Thank you so much for being so involved btw.

And to answer your question... no, I am not aware of any issues (I had it scan some of my binaries without problem). Maybe the size of the file is an issue?

**Comment by overfl0wd** [comment]
Happy to help! Looks like it's having a hard time chewing through a 692M repo 😅
![image](https://user-images.githubusercontent.com/48800966/59688248-500d6100-91ab-11e9-954a-96ef2b9592e9.png)

**Comment by kootenpv** [comment]
Haha, yea that is not the easiest task... maybe excluding filetypes could help or is that 692M all needed to be searched actually :thinking:?

**Comment by overfl0wd** [comment]
Here's the exclusion list (being removed prior to scanning) from the above example: `".exe" ".EXE" ".dll" ".DLL" ".bin" ".BIN" ".gif" ".GIF" ".css" ".png" ".PNG" ".jpg" ".JPG" ".jpeg" ".JPEG" ".bmp" ".BMP" ".js.map" ".htm" ".html"`

However, I just took a look at the repos with ncdu and found that <b>.git/objects/*.pack</b> files were absolutely massive. Some seemed to be half the size of the entire cloned repository. I'll be giving the scans a shot now that these are removed as well. 

To your earlier point, I think taking into account .gitignore might solve a lot of these problems

**Comment by kootenpv** [comment]
Note: `ncdu` is amazing (though I always keep forgetting the name).

The point of gittyleaks is to actually scan your whole git history (which very often indeed contain some massive-not-used-anymore-files). I think in your case that's actually annoying and you would be more interested in a more shallow search...

**Comment by overfl0wd** [comment]
..I've since learned more about Git and realized that those pack files are crucial to the process here 😅 in our use case we definitely do want to scan the whole history, I just admittedly didn't know enough about the inner-workings of Git to realize that deleting those broke everything.

**Comment by overfl0wd** [comment]
I added a little more verbosity in the error output to get a better sense of what's going on. I've had a 600MB repo hanging for 18hrs now so I figure something else must be up. I'm getting the following error when running on this (and similarly failing) repos.

![image](https://user-images.githubusercontent.com/48800966/59855023-1753c000-9342-11e9-92c1-a06889149939.png)

![image](https://user-images.githubusercontent.com/48800966/59854993-099e3a80-9342-11e9-8d49-4d8c66bc349a.png)

Just wanted to share, but I will continue debugging!

**Comment by overfl0wd** [comment]
I'm going to close this for now, I think it's just big files. Watching the processes via top, I can see that the program IS actually chewing through revisions despite seemingly "hanging" visually.

**Comment by nroose** [comment]
Any more info about this? We have a large repo, but not really large files. I currently think it is a file encoding error, because we have had that issue with other tools and that is what the error actually says. Seems like that should be fixable, though? Or at least document what encodings are supported?
