### ISSUE TITLE
Argparser / README inconsistencies 

### ISSUE THREAD

**Issue by skoslowski** [kootenpv/gittyleaks#2]
The README mentions the flag "--verbose" which actually only works with a single dash.

**Comment by kootenpv** [comment]
Thanks yet again! Very helpful...! If you can confirm it works now, I'll close the issue.

**Comment by skoslowski** [comment]
Sure thing. Just yesterday I found myself running "git filter-branch" to remove some api keys. Now I know I got them all. Really a nice tool!

**Comment by kootenpv** [comment]
Glad it helped :) ! Maybe you want to be involved with brainstorming on how to help the tool with suggesting automatic fixes or something?

**Comment by skoslowski** [comment]
Well, I suppose you could include a feature to remove certain phrases from (specific files) in the git history. I used find + sed, but I suppose an interactive command to select actions like single removal, remove all future, skip, ... for each find would make this process really convenient.
