### ISSUE TITLE
Funky image in README

### ISSUE THREAD

**Issue by lmas** [kootenpv/gittyleaks#3]
Hey, just a minor nitpick on the README when you're stuck on a small screen. I would suggest moving the text to below the image instead.

Other than that, thanks for such a great and important tool!

![gitty](https://cloud.githubusercontent.com/assets/4338013/9257639/ecd45632-41f6-11e5-9afc-6871955bf1c0.png)

**Comment by kootenpv** [comment]
Thanks a lot for taking the effort of creating an issue for it! Yea, I guess people don't use a table like that for a reason! The issue with the image is that it is very long, so it would look pretty weird I think if it is just at the top.... Still, I'll see what I can do.

**Comment by kootenpv** [comment]
Updated it in commit f51dbec , should be fixed?

**Comment by lmas** [comment]
Yep, looking better now. Thanks man!
